accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView
from django.urls import path

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'), # 경로, 뷰, 이름 순서로 적기
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'), # 경로, 로직 함수(클래스일 때 as.view() 사용), 이름
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

practice_01/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'), # 메인 페이지

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')), # 주소창에 이거를 치면 accounts에서 하위 분기를 한다는 뜻
    path('profiles/', include('profileapp.urls')), # 여기 적힌 url이 profileapp의 urls에 적힌 app_name을 뜻함
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')), # include: commentapp에서 하위 분기
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 개발 환경에서 이미지를 제공해 줄 수 있는 코드 (배포용에 사용하면 안 됨)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
    # 제일 처음에 mainapp의 url에서 update로 분기했기 때문에 각 앱 안에서 이름이 겹쳐도 괜찮
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False) # max_length가 최대 길이 문자열

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True) # null: 입력하지 않아도 된다는 게 아니라 db 내에서 null이 가능하다는 것
    # ForeignKey: 1대다로 연결해 주는 것 -> 한사람이 게시글 하나만 쓸 수 있는 것은 아니기 때문에
    # related_name: 유저와 연결되어 있는 article을 접근할 때 쓰는 이름
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True, blank=True) # blank: 입력할 때 넣지 않아도 된다는 것
    # related_name: 게시에서 게시글을 접근할 때 사용하는 것
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True) # 핀터레스트 기반이라 이미지에 null을 주면 복잡해짐 -> 걍 없이 할 것
    # upload_to: media 폴더 내에 article이라는 폴더를 새로 생성해 거기에 이미지 저장
    content = models.TextField(null=True, blank=True)
    # TestField: 긴 텍스트를 받을 때 쓰는 것
    created_at = models.DateField(auto_now_add=True)
    # auto_now_add: 굳이 서버에 설정하거나 사용자에게 입력받지 않아도 db에 생성된 시간을 기록해 자동으로 출력하는 것
    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld
from articleapp.models import Article


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm # 입력 폼을 뭘 쓸건지
    # success_url = reverse_lazy('accountapp:hello_world') # 클래스에서는 reverse 대신 reverse_lay 사용
    template_name = 'accountapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk}) # 여기서 self.object가 지칭하는 것은 target_user


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user' # html에서 특정 객체에 접근하는 이름 지정
    template_name = 'accountapp/detail.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)


has_ownership = [login_required, account_ownership_required]


@method_decorator(has_ownership, 'get') # get, post는 클래스 안에 들어 있는 메소드이기 때문에 이런 형식으로 적어야 함
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('articleapp:list')
    context_object_name = 'target_user'
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Sign Up</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Quit</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {%  csrf_token %}
            <div class="m-5">
                <input type="submit" class="btn btn-danger rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" class="profile_image m-4" alt="profile image">
            <h2 class="NNS_B">
                {{ target_user.profile.nickname }}
                {% if user == target_user %}
                    <a href="{%  url 'profileapp:update' pk=target_user.profile.pk %}" class="material-icons round_button">edit</a> <!-- edit라는 이름에서 아이콘이 결정됨 -->
                {% endif %}
            </h2> <!-- relate_name에 적어준 속성 때문에 prfile.으로 접근 가능 -->
            <h5>{{ target_user.profile.message }}</h5>
        {% else %}
            <h2 class="NNS_B"><a href="{% url 'profileapp:create' %}">Create Profile</a></h2>
        {% endif %}
    </div>
    <!-- <div>
        {{ target_user.date_joined }}
    </div> -->

    {% if user == target_user %}
    <div>
        <a href="{% url 'accountapp:update' pk=target_user.pk %}" class="material-icons round_button mx-1">settings</a> <!-- mx-1: 마진을 수평방향으로 1만큼 -->
        <a href="{% url 'accountapp:delete' pk=target_user.pk %}" class="material-icons round_button mx-1">close</a>
    </div>
    {% endif %}
</div>
<div>
    {% include 'snippets/list_fragment.html' with article_list=object_list %}
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Login</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}", method="post">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Update Info</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

{% endblock %}