articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

practice_01/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'), # 메인 페이지

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')), # 주소창에 이거를 치면 accounts에서 하위 분기를 한다는 뜻
    path('profiles/', include('profileapp.urls')), # 여기 적힌 url이 profileapp의 urls에 적힌 app_name을 뜻함
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')), # include: commentapp에서 하위 분기
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 개발 환경에서 이미지를 제공해 줄 수 있는 코드 (배포용에 사용하면 안 됨)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True) # null: 입력하지 않아도 된다는 게 아니라 db 내에서 null이 가능하다는 것
    # ForeignKey: 1대다로 연결해 주는 것 -> 한사람이 게시글 하나만 쓸 수 있는 것은 아니기 때문에
    # related_name: 유저와 연결되어 있는 article을 접근할 때 쓰는 이름
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True, blank=True) # blank: 입력할 때 넣지 않아도 된다는 것
    # related_name: 게시에서 게시글을 접근할 때 사용하는 것
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True) # 핀터레스트 기반이라 이미지에 null을 주면 복잡해짐 -> 걍 없이 할 것
    # upload_to: media 폴더 내에 article이라는 폴더를 새로 생성해 거기에 이미지 저장
    content = models.TextField(null=True, blank=True)
    # TestField: 긴 텍스트를 받을 때 쓰는 것
    created_at = models.DateField(auto_now_add=True)
    # auto_now_add: 굳이 서버에 설정하거나 사용자에게 입력받지 않아도 db에 생성된 시간을 기록해 자동으로 출력하는 것
    like = models.IntegerField(default=0)

templates/snippets/list_fragment.html
{% load static %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }

        .container div {
            width: 45%;
            max-width: 200px;
            display: flex; {# 이 속성 때문에 제목을 span 태그로 넣으면 사진과 제목이 세로가 아닌 가로로 배치됨 #}
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
            flex-direction: column;
            box-shadow: 0 0 1rem darkgrey;
        }

        div img{
            width: 100%;
            border-radius: 1rem;
        }
    </style>

    <div class="container my-3">
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}", alt="">
                </a>
                <span class="NNS_B m-2">{{ article.title }}</span>
            </div>
        {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script> <!-- 제일 상단에 load static 하고 적기 -->

    {% include 'snippets/pagination.html' %}

    <div class="text-center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}" class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

templates/snippets/pagination.html
<div class="text-center my-5">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary rounded-pill"> {# get 방식으로 넘겨줄때 ? 뒤에 적기 #}
            {{ page_obj.previous_page_number }}
        </a>
        {% endif %}
        <a href="#" class="btn btn-dark rounded-pill">
            {{ page_obj.number }} {# 현재 페이지 넘버 #}
        </a>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary rounded-pill"> {# get 방식은 ? 뒤에 적기 #}
            {{ page_obj.next_page_number }}
        </a>
        {% endif %}
    </div>