articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

practice_01/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'), # 메인 페이지

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')), # 주소창에 이거를 치면 accounts에서 하위 분기를 한다는 뜻
    path('profiles/', include('profileapp.urls')), # 여기 적힌 url이 profileapp의 urls에 적힌 app_name을 뜻함
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')), # include: commentapp에서 하위 분기
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 개발 환경에서 이미지를 제공해 줄 수 있는 코드 (배포용에 사용하면 안 됨)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True) # null: 입력하지 않아도 된다는 게 아니라 db 내에서 null이 가능하다는 것
    # ForeignKey: 1대다로 연결해 주는 것 -> 한사람이 게시글 하나만 쓸 수 있는 것은 아니기 때문에
    # related_name: 유저와 연결되어 있는 article을 접근할 때 쓰는 이름
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True, blank=True) # blank: 입력할 때 넣지 않아도 된다는 것
    # related_name: 게시에서 게시글을 접근할 때 사용하는 것
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True) # 핀터레스트 기반이라 이미지에 null을 주면 복잡해짐 -> 걍 없이 할 것
    # upload_to: media 폴더 내에 article이라는 폴더를 새로 생성해 거기에 이미지 저장
    content = models.TextField(null=True, blank=True)
    # TestField: 긴 텍스트를 받을 때 쓰는 것
    created_at = models.DateField(auto_now_add=True)
    # auto_now_add: 굳이 서버에 설정하거나 사용자에게 입력받지 않아도 db에 생성된 시간을 기록해 자동으로 출력하는 것
    like = models.IntegerField(default=0)

articleapp/forms.py
from django import forms
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable', 'style': 'text-align: left;' 'min-height: 10rem;'})) # 클래스를 적용하여 medium editor가 동작하도록 함
    class Meta:
        model = Article
        fields = ['title', 'image', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20 # 한 페이지에 몇개의 이미지를 출력할 것인지

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
{# 게시글 작성에만 medium editor을 적용하기 때문에 head.html이 아닌 여기에 붙여넣기 -> head.html에 작성하면 모든 페이지에 적용되어 트래픽 낭비됨 #}
<link rel="stylesheet" href="{% static 'beagle.css' %}">

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Create Article</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:create' %}" method="post", enctype="multipart/form-data">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Delete Article : {{ target_article.title }}</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {%  csrf_token %}
            <div class="m-5">
                <input type="submit" class="btn btn-danger rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center">
    <div class="my-5">
        {# 제목 / 글쓴이 / 날짜 #}
        <h1 class="NNS_B">{{ target_article.title }}</h1>
        <div class="my-3">
            <a href="{% url 'likeapp:article_like' article_pk=target_article.pk %}" class="material-icons" style="vertical-align: middle; color: #f77;">
                favorite
            </a>
            <span style="vertical-align: middle;">{{ target_article.like }}</span>
        </div>
        <h4>{{ target_article.writer.profile.nickname }}</h4>
        <p>{{ target_article.create_at }}</p>
    </div>
    <hr>
    <div class="my-5">
        {# 게시글 내용 #}
        {# 이미지에 빈칸을 주고 싶으면 이거 작성 {% if target_article.image %} #}
        <img src="{{ target_article.image.url }}" alt="" class="article_image">
        <div class="article_content">
            {{ target_article.content | safe }} {# safe: 위험한 태그를 삭제하고, 우리가 적용한 건 화면에 나타내줌 #}
        </div>
        {% if target_article.writer == user %}
        <div>
            <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-success rounded-pill px-5">
                Update
            </a>
            <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-danger rounded-pill px-5">
                Delete
            </a>
        </div>
        {% endif %}
    </div>
    <hr>
    <div>
        {# 여기에 댓글 #}
        {% for comment in target_article.comment.all %} {# comment: related_name #}
            <div class="comment_box">
                <div>
                    <span style="font-size: 1.3rem;" class="NNS_B">
                        {{ comment.writer.profile.nickname }}
                    </span>
                    <span>
                        {{ comment.created_at }}
                    </span>
                </div>
                <div class="my-2">
                    <p>{{ comment.content }}</p>
                </div>
                {% if comment.writer == user %}
                    <div style="text-align: right">
                        <a href="{% url 'commentapp:delete' pk=comment.pk %}" class="btn btn-danger rounded-pill px-5">Delete</a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        {% include 'commentapp/create.html' %}
    </div>
</div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }

        .container div {
            width: 45%;
            max-width: 200px;
            display: flex; {# 이 속성 때문에 제목을 span 태그로 넣으면 사진과 제목이 세로가 아닌 가로로 배치됨 #}
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
            flex-direction: column;
            box-shadow: 0 0 1rem darkgrey;
        }

        div img{
            width: 100%;
            border-radius: 1rem;
        }
    </style>

    <div class="container my-3">
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}", alt="">
                </a>
                <span class="NNS_B m-2">{{ article.title }}</span>
            </div>
        {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script> <!-- 제일 상단에 load static 하고 적기 -->

    {% include 'snippets/pagination.html' %}

    <div class="text-center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}" class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
{# 게시글 작성에만 medium editor을 적용하기 때문에 head.html이 아닌 여기에 붙여넣기 -> head.html에 작성하면 모든 페이지에 적용되어 트래픽 낭비됨 #}
<link rel="stylesheet" href="{% static 'beagle.css' %}">

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Update Article</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post", enctype="multipart/form-data">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}